apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.domain }}-mcp-server
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.domain }}-mcp-server
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}